### ISSUE TITLE
Create xml Folders, Update fragment Folders

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/WishBoard#12]
- [x] 폴더 fragment에 관한 xml 작성
- [x] 폴더 선택에 필요한 리스트뷰 작성

// 폴더의 popup 관련 xml은 추후에 진행 예정 (정기회의에서 결정된 사항)

**Comment by youngjinc** [comment]
fragment_folder.xml에서 RecyclerView에 layout_marginTop = "15dp" 추가 부탁드립니다.

**Comment by hyejungg** [comment]
수정사항 및 upload 후 이슈닫습니다.
