### ISSUE TITLE
Modify activity for Cart 

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/WishBoard#142]
장바구니 추가 기능 구현 필요
- [x] 장바구니에서 item_image 보여지는 처리

---------------------------
사이클뷰 내 클릭 이벤트 구현(+/-/x버튼)

- [x] 클릭이벤트 구현
- [x] 수량 변화를 display
- [x] 수량 변화를 db에 저장
- [ ] 이미 장바구니에 값이 존재하는 경우 insert 불가하도록 addCart시 예외처리 필요
    - 타임에러 발생
- [x] ItemAdapter의 cart 동그라미 버튼 등록된 경우에는 계속 눌러놓게 해놔야 함
- [x] 수량 변화를 2개 이상일 때 발생하는 에러 수정
    - 서버쪽 에러 해결 필요
- [x] 총합계금액 display 이상현상 해결 -> **_생명주기 처리하면서 해결함_**

**Comment by hyejungg** [comment]
@youngjinc 

- [ ] 이미 장바구니에 값이 존재하는 경우 insert 불가하도록 addCart시 예외처리 필요
타임에러 발생

이 부분 장바구니에 추가하는 경우는 홈화면에서 버튼 누를 때 말고는 없는데 장바구니에 들어갔다면 -> 초록버튼으로 바뀌었으니 또 추가하는 경우는 없을테니 이 부분은 별도 처리를 안해도 될 것 같은데 어찌 생각하시나용?

**Comment by youngjinc** [comment]
> @youngjinc
> 
> * [ ]  이미 장바구니에 값이 존재하는 경우 insert 불가하도록 addCart시 예외처리 필요
>   타임에러 발생
> 
> 이 부분 장바구니에 추가하는 경우는 홈화면에서 버튼 누를 때 말고는 없는데 장바구니에 들어갔다면 -> 초록버튼으로 바뀌었으니 또 추가하는 경우는 없을테니 이 부분은 별도 처리를 안해도 될 것 같은데 어찌 생각하시나용?
> 동의하신다면 이 부분은 넘어가도록 하겠습니다!
