### ISSUE TITLE
Create activity and xml for AddItem, LinkSharing

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/WishBoard#7]
- [x] 아이템 등록(수동) activity, xml 작성

- [x] 아이템 등록(자동) activity, xml 작성 //LinkSharing
- [x] 공유목록에 위시보드 앱 추가
- [x] 링크공유 팝업창 xml에서 알림 유형 스피너 커스텀
- [x] 팝업창에 필요한 리소스(팝업창 배경, 스타일, 메모 배경, 알림유형 배열) 생성

**Comment by hyejungg** [comment]
슬랙에서 논의 후 아이템 검색 구현 계획 변경
-> 다음 릴리즈 때 개발.

**Comment by youngjinc** [comment]
아이템 검색은 다음 릴리즈 때 개발할 것이므로 이슈 타이틀에서 SearchItem과 설명 내용에서 아이템 검색 부분은 제외해서 이슈 수정하면 좋을 것 같음

**Comment by hyejungg** [comment]
@youngjinc 지금 확인했따.
1. 아이템 등록 중 자동으로 등록을 같이 진행하니까 추가해도 좋을 것 같아! 
2. 지금 수정하겠습니다!

**Comment by youngjinc** [comment]
fragment_new_item.xml(수동등록)에서 아이템 이미지 뷰에 scaleType="center" 추가 부탁드립니다.

**Comment by youngjinc** [comment]
상품명, 이미지, 가격데이터 가져오는 법오픈그래프로 메타태그 가져오기 https://hamzzibari.tistory.com/68
